import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { CheckCircle2, LoaderCircle } from 'lucide-react'
import { useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ErrorState } from '../components/StateViews'
import { getRankingStatus } from '../services/status'
const stages = ['Loading Candidates', 'Parsing Dataset', 'Extracting Features', 'Building Embeddings', 'Calculating Scores', 'Generating Submission', 'Creating Output Files']
export function ProcessingPage() { const { id = '' } = useParams(); const navigate = useNavigate(); const query = useQuery({ queryKey: ['status', id], queryFn: () => getRankingStatus(id), refetchInterval: data => data.state.data?.status === 'completed' || data.state.data?.status === 'failed' ? false : 2000 }); const job = query.data; useEffect(() => { if (job?.status === 'completed') navigate(`/results/${id}`, { replace: true }) }, [id, job?.status, navigate]); if (query.isError || job?.status === 'failed') return <ErrorState message={query.isError ? 'The backend has no reachable ranking-status endpoint. Start the API adapter or configure VITE_API_BASE_URL.' : job?.error ?? 'The ranking engine reported a processing failure. Please check the uploaded candidate schema and retry.'} retry={() => query.refetch()}/>; const progress = Math.max(4, Math.min(100, job?.progress ?? 4)); const active = job?.step ?? 'Waiting for ranking service'; return <section className="mx-auto max-w-xl text-center"><motion.div animate={{ rotate: 360 }} transition={{ duration: 2.5, repeat: Infinity, ease: 'linear' }} className="mx-auto mb-7 grid size-20 place-items-center rounded-[28px] bg-indigo-500/15 text-indigo-300"><LoaderCircle size={38}/></motion.div><p className="eyebrow">Ranking in progress</p><h1 className="mt-3 text-3xl font-bold">Preparing your candidate shortlist</h1><p className="mt-3 text-slate-400">{active}</p><div className="surface mt-9 overflow-hidden p-6 text-left"><div className="mb-3 flex justify-between text-sm"><span className="text-slate-300">Processing status</span><span className="font-medium text-indigo-300">{progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><motion.div animate={{ width: `${progress}%` }} className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-blue-400"/></div><div className="mt-7 space-y-3">{stages.map((stage, index) => <div key={stage} className="flex items-center gap-3 text-sm"><CheckCircle2 size={17} className={index < stages.indexOf(active) ? 'text-emerald-400' : stage === active ? 'text-indigo-300' : 'text-slate-700'}/><span className={stage === active ? 'font-medium text-white' : 'text-slate-500'}>{stage}</span></div>)}</div></div></section> }
