import { useQuery } from '@tanstack/react-query'
import { Download, FileArchive, FileSpreadsheet, FileText } from 'lucide-react'
import { useState } from 'react'
import { useParams } from 'react-router-dom'
import { CandidateDrawer } from '../components/CandidateDrawer'
import { ErrorState, EmptyState } from '../components/StateViews'
import { RankingTable } from '../components/RankingTable'
import { getDownloads } from '../services/download'
import { getResults } from '../services/results'
import type { Candidate, RankingResults } from '../types/api'
const cards: Array<{ key: keyof RankingResults['summary']; label: string; suffix?: string }> = [{ key: 'candidatesUploaded', label: 'Candidates uploaded' }, { key: 'candidatesRanked', label: 'Candidates ranked' }, { key: 'filteredCandidates', label: 'Filtered candidates' }, { key: 'averageMatchScore', label: 'Average match score', suffix: '%' }, { key: 'processingTime', label: 'Processing time' }]
export function ResultsPage() { const { id = '' } = useParams(); const [selected, setSelected] = useState<Candidate>(); const results = useQuery({ queryKey: ['results', id], queryFn: () => getResults(id) }); const downloads = useQuery({ queryKey: ['downloads', id], queryFn: () => getDownloads(id) }); if (results.isLoading) return <section className="space-y-5">{[1, 2, 3].map(x => <div key={x} className="surface h-32 animate-pulse"/>)}</section>; if (results.isError || !results.data) return <ErrorState message="Results could not be loaded. Confirm that the backend exposes GET /rankings/:id/results." retry={() => results.refetch()}/>; const data = results.data; const summary = data.summary; return <section><div className="mb-8"><p className="eyebrow">Ranking complete</p><h1 className="mt-2 text-3xl font-bold">Candidate intelligence report</h1><p className="mt-2 text-slate-400">Review the engine’s ranked output and export its deliverables.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(card => { const value = summary[card.key]; return <article key={card.key} className="surface p-5"><p className="text-sm text-slate-400">{card.label}</p><p className="mt-3 text-2xl font-bold">{value ?? '—'}{value != null && card.suffix}</p></article> })}</div><div className="mt-8">{data.candidates.length ? <RankingTable candidates={data.candidates} onView={setSelected}/> : <EmptyState title="No ranked candidates" detail="The backend returned no ranked candidates for this job."/>}</div><section className="mt-8"><div className="mb-4"><p className="eyebrow">Exports</p><h2 className="mt-1 text-xl font-semibold">Downloads</h2></div>{downloads.isLoading ? <div className="grid gap-4 md:grid-cols-3">{[1, 2, 3].map(x => <div key={x} className="surface h-36 animate-pulse"/>)}</div> : downloads.isError || !downloads.data?.length ? <EmptyState title="No downloads available" detail="Generated files will appear here when provided by the backend."/> : <div className="grid gap-4 md:grid-cols-3">{downloads.data.map((file, index) => <a key={file.url} href={file.url} className="surface group p-5 transition hover:-translate-y-1 hover:border-indigo-500/50"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-indigo-500/10 text-indigo-300">{index === 0 ? <FileSpreadsheet size={20}/> : index === 1 ? <FileText size={20}/> : <FileArchive size={20}/>}</span><Download size={18} className="text-slate-500 transition group-hover:text-indigo-300"/></div><h3 className="mt-5 font-semibold">{file.label}</h3><p className="mt-1 text-sm text-slate-400">{file.description}</p></a>)}</div>}</section><CandidateDrawer rankingId={id} candidate={selected} onClose={() => setSelected(undefined)}/></section> }
