import { useMutation } from '@tanstack/react-query'
import { ArrowRight, Sparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { UploadCard } from '../components/UploadCard'
import { apiError } from '../services/api'
import { createRanking } from '../services/upload'
export function UploadPage() { const [candidates, setCandidates] = useState<File>(); const [jobDescription, setJobDescription] = useState<File>(); const [metadata, setMetadata] = useState<File>(); const navigate = useNavigate(); const ranking = useMutation({ mutationFn: () => createRanking({ candidates: candidates!, jobDescription: jobDescription!, metadata }), onSuccess: job => navigate(`/processing/${job.id}`) }); return <motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-4xl"><div className="mb-10 text-center"><p className="eyebrow mb-3"><Sparkles size={14} className="mr-1 inline"/>Ranking Workspace</p><h1 className="text-3xl font-bold tracking-tight sm:text-5xl">Nexoprep Candidate Ranking System</h1><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-slate-400">Upload the required files and let the ranking engine process candidates.</p></div><div className="grid gap-4 md:grid-cols-3"><UploadCard title="Candidates Dataset" description="JSONL or JSON dataset" accept={{ 'application/json': ['.jsonl', '.json'] }} file={candidates} required onFile={setCandidates}/><UploadCard title="Job Description" description="TXT, PDF, or DOCX" accept={{ 'text/plain': ['.txt'], 'application/pdf': ['.pdf'], 'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'] }} file={jobDescription} required onFile={setJobDescription}/><UploadCard title="Optional Metadata" description="YAML configuration" accept={{ 'application/x-yaml': ['.yaml', '.yml'] }} file={metadata} onFile={setMetadata}/></div>{ranking.isError && <p className="mt-4 rounded-xl border border-rose-500/20 bg-rose-500/5 p-3 text-center text-sm text-rose-200">Upload failed: {apiError(ranking.error)}</p>}<div className="mt-8 flex flex-col items-center justify-between gap-4 border-t border-slate-800 pt-6 sm:flex-row"><p className="text-sm text-slate-500"> <span className="text-indigo-300"></span> </p><button disabled={!candidates || !jobDescription || ranking.isPending} onClick={() => ranking.mutate()} className="btn-primary min-w-44">{ranking.isPending ? 'Submitting files…' : <>Start Ranking <ArrowRight size={17}/></>}</button></div></motion.section> }
